"""
PhyFix SEO Suite — Tool 5: Sitemap & Robots.txt Generator
Generates a fresh XML sitemap and an optimised robots.txt prioritising
high-value tutoring pages. Also validates the existing sitemap.
"""

import os
import re
import defusedxml.minidom
from datetime import date
from colorama import Fore, Style, init
from config import SITE_URL, STATIC_ROUTES, TOPIC_SLUGS, ALL_ROUTES, PRIORITY_PAGES

init(autoreset=True)

TODAY = date.today().isoformat()

URL_CONFIG = {
    "/": {"priority": "1.0", "changefreq": "weekly"},
    "/teachers": {"priority": "0.95", "changefreq": "daily"},
    "/physics-classes": {"priority": "0.92", "changefreq": "monthly"},
    "/maths-classes": {"priority": "0.92", "changefreq": "monthly"},
    "/free-demo": {"priority": "0.92", "changefreq": "monthly"},
    "/ib-physics-tutor": {"priority": "0.90", "changefreq": "monthly"},
    "/igcse-math-tutor": {"priority": "0.90", "changefreq": "monthly"},
    "/a-level-physics-tutor": {"priority": "0.90", "changefreq": "monthly"},
    "/online-math-tutor": {"priority": "0.88", "changefreq": "monthly"},
    "/about": {"priority": "0.80", "changefreq": "monthly"},
    "/blog": {"priority": "0.85", "changefreq": "weekly"},
    "/contact": {"priority": "0.80", "changefreq": "monthly"},
    "/resources": {"priority": "0.82", "changefreq": "weekly"},
    "/practice": {"priority": "0.78", "changefreq": "weekly"},
    "/pricing": {"priority": "0.75", "changefreq": "monthly"},
    "/how-it-works": {"priority": "0.72", "changefreq": "monthly"},
    "/become-tutor": {"priority": "0.70", "changefreq": "monthly"},
    # Topic pages
    **{f"/topics/{slug}": {"priority": "0.85", "changefreq": "monthly"} for slug in TOPIC_SLUGS},
}

BLOG_SLUGS = [
    "ib-physics-waves-complete-guide",
    "igcse-maths-quadratics-mastery",
    "a-level-physics-fields-guide",
    "ap-physics-1-study-plan",
    "cbse-vs-icse-physics",
    "one-on-one-tutoring-benefits",
    "ib-maths-aa-vs-ai",
    "igcse-vs-o-level",
    "common-physics-mistakes",
    "ap-calculus-ab-study-guide",
    "top-20-most-demanded-tutoring-subjects-globally-2024-2026",
]

ROBOTS_CONTENT = """# robots.txt for PhyFix
# https://phyfix.com
# Generated by PhyFix SEO Suite

User-agent: *
Allow: /

# Priority crawling hints for Googlebot
User-agent: Googlebot
Allow: /
Crawl-delay: 0

# Allow Bingbot
User-agent: Bingbot
Allow: /
Crawl-delay: 1

# AI training crawlers — block if desired (uncomment to block)
# User-agent: GPTBot
# Disallow: /

# Block admin & API routes
User-agent: *
Disallow: /api/
Disallow: /admin/
Disallow: /dashboard/
Disallow: /*.json$

# Block sensitive static assets
Disallow: /google8a6929c81d71a7ec.html

# Sitemap locations
Sitemap: https://phyfix.com/sitemap.xml
"""


def generate_sitemap_xml(include_blog: bool = True, output_path: str = None) -> str:
    """Generate a clean, optimised XML sitemap."""
    urls = []

    # Core static routes
    for route in STATIC_ROUTES:
        if route in URL_CONFIG:
            cfg = URL_CONFIG[route]
        else:
            cfg = {"priority": "0.65", "changefreq": "monthly"}
        urls.append((route, cfg["priority"], cfg["changefreq"]))

    # Topic pages
    for slug in TOPIC_SLUGS:
        route = f"/topics/{slug}"
        cfg = URL_CONFIG.get(route, {"priority": "0.85", "changefreq": "monthly"})
        urls.append((route, cfg["priority"], cfg["changefreq"]))

    # Blog posts
    if include_blog:
        for slug in BLOG_SLUGS:
            urls.append((f"/blog/{slug}", "0.75", "monthly"))

    # Legal/policy pages
    for route in ["/terms", "/privacy", "/refund"]:
        urls.append((route, "0.30", "yearly"))

    # Build XML
    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"')
    lines.append('        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"')
    lines.append('        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9')
    lines.append('          http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">')

    # Group by category for readability
    groups = {
        "Core Pages": [u for u in urls if u[0] in ["/", "/teachers", "/about", "/contact", "/blog", "/resources", "/practice", "/pricing", "/how-it-works", "/become-tutor"]],
        "SEO Landing Pages": [u for u in urls if u[0] in ["/physics-classes", "/maths-classes", "/free-demo", "/ib-physics-tutor", "/igcse-math-tutor", "/a-level-physics-tutor", "/online-math-tutor"]],
        "IB Physics Topics": [u for u in urls if "/topics/ib-physics" in u[0]],
        "IGCSE Physics Topics": [u for u in urls if "/topics/igcse-physics" in u[0]],
        "A-Level Physics Topics": [u for u in urls if "/topics/a-level-physics" in u[0]],
        "AP Physics Topics": [u for u in urls if "/topics/ap-physics" in u[0]],
        "IB Maths Topics": [u for u in urls if "/topics/ib-maths" in u[0]],
        "IGCSE Maths Topics": [u for u in urls if "/topics/igcse-maths" in u[0]],
        "AP Calculus Topics": [u for u in urls if "/topics/ap-calculus" in u[0]],
        "CBSE Topics": [u for u in urls if "/topics/cbse" in u[0]],
        "Blog Posts": [u for u in urls if "/blog/" in u[0]],
        "Legal": [u for u in urls if u[0] in ["/terms", "/privacy", "/refund"]],
    }

    for group_name, group_urls in groups.items():
        if not group_urls:
            continue
        lines.append(f"\n  <!-- {group_name} -->")
        for route, priority, changefreq in group_urls:
            lines.append("  <url>")
            lines.append(f"    <loc>{SITE_URL}{route}</loc>")
            lines.append(f"    <lastmod>{TODAY}</lastmod>")
            lines.append(f"    <changefreq>{changefreq}</changefreq>")
            lines.append(f"    <priority>{priority}</priority>")
            lines.append("  </url>")

    lines.append("\n</urlset>")
    xml_content = "\n".join(lines)

    # Write to client/public/sitemap.xml (canonical location)
    canonical_path = "client/public/sitemap.xml"
    with open(canonical_path, "w", encoding="utf-8") as f:
        f.write(xml_content)

    # Also write to output dir if specified
    if output_path:
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(xml_content)

    return xml_content


def validate_sitemap(xml_content: str) -> dict:
    """Validate the generated sitemap XML."""
    issues = []
    warnings = []

    # Check well-formed XML
    try:
        defusedxml.minidom.parseString(xml_content.encode("utf-8"))
        passed_xml = True
    except Exception as e:
        issues.append(f"Invalid XML: {e}")
        passed_xml = False

    # Count URLs
    url_count = xml_content.count("<url>")

    # Check for duplicate URLs
    locs = re.findall(r"<loc>(.*?)</loc>", xml_content)
    duplicates = [l for l in locs if locs.count(l) > 1]
    if duplicates:
        issues.append(f"Duplicate URLs found: {list(set(duplicates))}")

    # Check priorities
    priorities = re.findall(r"<priority>(.*?)</priority>", xml_content)
    invalid_priorities = [p for p in priorities if not (0.0 <= float(p) <= 1.0)]
    if invalid_priorities:
        issues.append(f"Invalid priorities: {invalid_priorities}")

    # Check all URLs start with site URL
    bad_locs = [l for l in locs if not l.startswith(SITE_URL)]
    if bad_locs:
        warnings.append(f"URLs not starting with {SITE_URL}: {bad_locs[:3]}")

    return {
        "valid_xml": passed_xml,
        "url_count": url_count,
        "issues": issues,
        "warnings": warnings,
        "unique_urls": len(set(locs)),
    }


def run_sitemap_generator(write_canonical: bool = True) -> dict:
    print(f"\n{Fore.CYAN}{'═'*60}")
    print(f"  PhyFix Sitemap & Robots.txt Generator")
    print(f"{'═'*60}{Style.RESET_ALL}\n")

    os.makedirs("seo/output", exist_ok=True)

    # 1. Generate sitemap
    print(f"  {Fore.YELLOW}● Generating XML Sitemap...{Style.RESET_ALL}")
    xml_content = generate_sitemap_xml(
        include_blog=True,
        output_path="seo/output/sitemap.xml",
    )

    # 2. Validate
    validation = validate_sitemap(xml_content)
    print(f"\n  {'─'*40}")
    print(f"  URLs in sitemap:  {Fore.GREEN}{validation['url_count']}{Style.RESET_ALL}")
    print(f"  Unique URLs:      {Fore.GREEN}{validation['unique_urls']}{Style.RESET_ALL}")
    if validation["valid_xml"]:
        print(f"  XML valid:        {Fore.GREEN}✓ Yes{Style.RESET_ALL}")
    else:
        print(f"  XML valid:        {Fore.RED}✗ No{Style.RESET_ALL}")
    for issue in validation["issues"]:
        print(f"  {Fore.RED}✗ Issue: {issue}{Style.RESET_ALL}")
    for warn in validation["warnings"]:
        print(f"  {Fore.YELLOW}⚠ Warning: {warn}{Style.RESET_ALL}")

    print(f"\n  {Fore.GREEN}✓ Sitemap written to client/public/sitemap.xml{Style.RESET_ALL}")
    print(f"  {Fore.GREEN}✓ Sitemap copy in seo/output/sitemap.xml{Style.RESET_ALL}")

    # 3. Priority pages summary
    print(f"\n  {Fore.YELLOW}● Priority Page Priorities:{Style.RESET_ALL}\n")
    for route in PRIORITY_PAGES:
        cfg = URL_CONFIG.get(route, {"priority": "0.70", "changefreq": "monthly"})
        bar = "█" * int(float(cfg["priority"]) * 10)
        print(f"  {bar:<10}  {cfg['priority']}  {route}")

    # 4. Generate robots.txt
    print(f"\n  {Fore.YELLOW}● Generating robots.txt...{Style.RESET_ALL}")
    robots_path = "client/public/robots.txt"
    with open(robots_path, "w", encoding="utf-8") as f:
        f.write(ROBOTS_CONTENT)
    print(f"  {Fore.GREEN}✓ robots.txt written to {robots_path}{Style.RESET_ALL}")

    # 5. Submission reminders
    print(f"\n  {Fore.CYAN}● Next Steps:{Style.RESET_ALL}")
    print(f"  1. Submit sitemap to Google Search Console:")
    print(f"     https://search.google.com/search-console/sitemaps")
    print(f"     URL: {SITE_URL}/sitemap.xml")
    print(f"  2. Submit sitemap to Bing Webmaster Tools:")
    print(f"     https://www.bing.com/webmasters/sitemaps")
    print(f"  3. Verify robots.txt is accessible:")
    print(f"     {SITE_URL}/robots.txt")
    print(f"  4. Test with Google Rich Results Test:")
    print(f"     https://search.google.com/test/rich-results")

    return {
        "sitemap_path": "client/public/sitemap.xml",
        "robots_path": robots_path,
        "validation": validation,
    }


if __name__ == "__main__":
    run_sitemap_generator()
